# Generated by Django 4.2.9 on 2024-02-15 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gearbox', models.CharField(blank=True, max_length=40, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Gearbox Preference',
                'verbose_name_plural': 'Gearbox Preference',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion', models.CharField(blank=True, max_length=40, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Promotion',
                'verbose_name_plural': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('number', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField()),
                ('gearbox', models.ForeignKey(blank=True, max_length=25, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.gearbox')),
                ('information', models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.promotion')),
            ],
            options={
                'verbose_name': 'Support History',
                'verbose_name_plural': 'Support History',
            },
        ),
    ]
